sylvan_library/conf/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include, re_path
from sylvan_library.frontend import views as frontend_views

urlpatterns = [
    # Django and API routes should come first
    path("website/", include("sylvan_library.website.urls")),
    path("api/cards/", include("sylvan_library.cards.urls")),
    path("admin/", admin.site.urls),
    path("api-auth/", include("rest_framework.urls", namespace="rest_framework")),
    path("tinymce/", include("tinymce.urls")),
]

if settings.DEBUG_TOOLBAR:
    import debug_toolbar

    urlpatterns.append(path("__debug__/", include(debug_toolbar.urls)))

# A catch-all route to render the React application.
# This should be the last pattern in the list.
urlpatterns.append(re_path(r"^react/.*$", frontend_views.index, name="react-app"))

sylvan_library/website/urls.py
"""
Urls for the website app
"""

from django.urls import path

from sylvan_library.website import views

# pylint: disable=invalid-name
app_name = "website"
urlpatterns = [
    path("", views.index, name="index"),
    path("search/", views.card_search, name="card_search"),
    path("set_list/", views.set_list, name="set_list"),
    path(
        "ajax/search_result_details/<int:printing_id>/",
        views.ajax_search_result_details,
        name="ajax_search_result_details",
    ),
    path(
        "ajax/search_result_rulings/<int:card_id>/",
        views.ajax_search_result_rulings,
        name="ajax_search_result_rulings",
    ),
    path(
        "ajax/search_result_languages/<int:printing_id>/",
        views.ajax_search_result_languages,
        name="ajax_search_result_languages",
    ),
    path(
        "ajax/search_result_ownership/<int:card_id>/",
        views.ajax_search_result_ownership,
        name="ajax_search_result_ownership",
    ),
    path(
        "ajax/search_result_add/<int:printing_id>/",
        views.ajax_search_result_add,
        name="ajax_search_result_add",
    ),
    path(
        "ajax/card_printing_image/<int:printing_id>/",
        views.ajax_card_printing_image,
        name="ajax_card_printing_image",
    ),
    path(
        "ajax/change_card_ownership",
        views.ajax_change_card_ownership,
        name="ajax_change_card_ownership",
    ),
    path(
        "ajax/ownership_summary/<int:card_id>/",
        views.ajax_ownership_summary,
        name="ajax_ownership_summary",
    ),
    path(
        "ajax/search_result_set_summary/<int:printing_id>/",
        views.ajax_search_result_set_summary,
        name="ajax_search_result_set_summary",
    ),
    path(
        "ajax/search_result_decks/<int:card_id>/",
        views.ajax_search_result_decks,
        name="ajax_search_result_decks",
    ),
    path(
        "ajax/search_result_links/<int:card_id>/",
        views.ajax_search_result_links,
        name="ajax_search_result_links",
    ),
    path(
        "ajax/search_result_prices/<int:card_printing_id>/",
        views.ajax_search_result_prices,
        name="ajax_search_result_prices",
    ),
    path(
        "ajax/search_result_price_json/<int:card_printing_id>/",
        views.ajax_search_result_price_json,
        name="ajax_search_result_price_json",
    ),
    # Decks
    path("decks/card/", views.deck_card_search, name="deck_card_search"),
    path("decks/", views.deck_list, name="decks"),
    path("decks/create/", views.deck_create, name="create_deck"),
    path("decks/stats", views.deck_stats, name="deck_stats"),
    path("decks/<int:deck_id>/", views.deck_view, name="deck_view"),
    path("decks/<int:deck_id>/edit", views.deck_edit, name="deck_edit"),
    path(
        "decks/<int:deck_id>/colour_weights",
        views.deck_colour_weights,
        name="deck_colour_weights",
    ),
    path(
        "decks/change_unused_decks",
        views.change_unused_decks,
        name="change_unused_decks",
    ),
]

sylvan_library/website/views.py
"""
Module for all website views
"""
import datetime
import logging
import random
import urllib.parse
import urllib.request
from typing import Dict, Any, List

from django.contrib.auth.models import User
from django.core.exceptions import ValidationError, PermissionDenied
from django.core.handlers.wsgi import WSGIRequest
from django.core.paginator import Paginator
from django.db import transaction
from django.db.models import Sum, Count, Q
from django.http import HttpResponse, JsonResponse
from django.shortcuts import render, redirect

from cards.models.card import (
    CardPrinting,
    Card,
    UserOwnedCard,
    CardLocalisation,
    CardFace,
    UserCardChange,
)
from cards.models.colour import Colour
from cards.models.decks import DeckCard, Deck
from cards.models.language import Language
from cards.models.sets import Set
from cards.models.user import UserProps
from website.forms import (
    QuerySearchForm,
    ChangeCardOwnershipForm,
    DeckForm,
)
from website.pagination import get_page_buttons

logger = logging.getLogger("django")


def index(request: WSGIRequest) -> HttpResponse:
    """
    The index page of this site
    :param request: The
    :return:
    """
    context = {"sets": Set.objects.all()}
    return render(request, "website/index.html", context)


def name_search(request: WSGIRequest) -> HttpResponse:
    """
    The view for when a user searches by card name
    :param request: The user's request
    :return: The HTTP Response
    """
    query_form = QuerySearchForm(request.GET)
    query_form.user = request.user
    search = query_form.get_search()
    return render(
        request,
        "website/simple_search.html",
        {
            "query_form": query_form,
            "results": search.results,
            "result_count": search.paginator.count,
            "page": search.page,
            "page_buttons": get_page_buttons(
                search.paginator, query_form.get_page_number(), 3
            ),
            "page_title": f"{search.query_string} - Sylvan Library"
            if search.query_string
            else "Sylvan Library",
            "pretty_query_message": search.get_pretty_str(),
            "error_message": search.error_message,
        },
    )


def ajax_search_result_details(request: WSGIRequest, printing_id: int) -> HttpResponse:
    """
    Gets the details of a card in the result page
    :param request: The user's request
    :param printing_id: The ID of the CardPrinting
    :return: The HTTP response
    """
    printing = CardPrinting.objects.get(id=printing_id)
    return render(
        request, "website/results/search_result_details.html", {"printing": printing}
    )


def ajax_search_result_rulings(request: WSGIRequest, card_id: int) -> HttpResponse:
    """
    Returns the rulings of a card
    :param request: The user's request
    :param card_id: The ID of the Card
    :return: The rulings HTML
    """
    card = Card.objects.get(id=card_id)
    return render(request, "website/results/search_result_rulings.html", {"card": card})


def ajax_search_result_languages(
    request: WSGIRequest, printing_id: int
) -> HttpResponse:
    """
    Gets the languages HTML of a printing
    :param request: The user's request
    :param printing_id: The CardPrinting ID
    :return: The languages HTML
    """
    printing = CardPrinting.objects.get(id=printing_id)
    return render(
        request, "website/results/search_result_languages.html", {"printing": printing}
    )


def ajax_card_printing_image(request: WSGIRequest, printing_id: int) -> HttpResponse:
    """
    Gets the image view of a printing
    :param request: The user's request
    :param printing_id: The CardPrinting ID
    :return: The image HTML
    """
    printing = CardPrinting.objects.get(id=printing_id)
    return render(request, "website/card_image.html", {"printing": printing})


def ajax_search_result_add(request: WSGIRequest, printing_id: int) -> HttpResponse:
    """
    Gets the "Add card" form for a card printing
    :param request: The user's request
    :param printing_id: The CardPrinting ID
    :return: The add form HTML
    """
    printing = CardPrinting.objects.get(id=printing_id)
    form = ChangeCardOwnershipForm(printing)
    return render(
        request,
        "website/results/search_result_add.html",
        {"form": form, "printing": printing},
    )


def ajax_search_result_ownership(request: WSGIRequest, card_id: int) -> HttpResponse:
    """
    Gets the ownership list for a Card
    :param request: The user's request
    :param card_id: The Card ID
    :return: The ownership HTML
    """
    card = Card.objects.get(id=card_id)
    ownerships = (
        UserOwnedCard.objects.filter(owner=request.user)
        .filter(card_localisation__card_printing__card__id=card_id)
        .order_by("card_localisation__card_printing__set__release_date")
    )
    changes = (
        UserCardChange.objects.filter(owner=request.user)
        .filter(card_localisation__card_printing__card__id=card_id)
        .order_by("date")
    )
    return render(
        request,
        "website/results/search_result_ownership.html",
        {"card": card, "ownerships": ownerships, "changes": changes},
    )


def ajax_change_card_ownership(request: WSGIRequest) -> HttpResponse:
    """
    Applies an ownership change (adding or removing the amount that a card owns)
    :param request: The user's request
    :return: JSON containing whether the change was successful or not
    """
    if not request.POST.get("count"):
        return JsonResponse({"result": False, "error": "Invalid count"})

    try:
        with transaction.atomic():
            change_count = int(request.POST["count"])
            localisation_id = int(request.POST["localisation"])
            localisation = CardLocalisation.objects.get(pk=localisation_id)
            localisation.apply_user_change(change_count, request.user)
            return JsonResponse({"result": True})
    except CardLocalisation.DoesNotExist as ex:
        return JsonResponse({"result": False, "error": str(ex)})


def ajax_ownership_summary(request: WSGIRequest, card_id: int) -> HttpResponse:
    """
    Gets the ownership HTML summary
    :param request: The user's request
    :param card_id: The Card ID
    :return: The ownership summary HTML
    """
    card = Card.objects.get(id=card_id)
    return render(request, "website/results/ownership_summary.html", {"card": card})


def ajax_search_result_set_summary(
    request: WSGIRequest, printing_id: int
) -> HttpResponse:
    """
    Gets the set summary for a given CardPrinting
    :param request: The user's request
    :param printing_id: The CardPrinting ID
    :return: The set summary HTML
    """
    printing = CardPrinting.objects.prefetch_related(
        "card__printings__rarity",
        "card__printings__localisations__ownerships",
        "card__printings__localisations__language",
        "card__printings__localisations__localised_faces__image",
        "card__printings__face_printings__localised_faces__image",
        "card__printings__face_printings__localised_faces__localisation",
        "card__printings__set",
        "card__printings__rarity",
    ).get(id=printing_id)

    return render(
        request,
        "website/results/search_result_sets.html",
        {"card": printing.card, "selected_printing": printing},
    )


def ajax_search_result_decks(request: WSGIRequest, card_id: int) -> HttpResponse:
    """
    Gets the deck list used by a given card
    :param request: The user's request
    :param card_id: The ID of the Card to get the HTML for
    :return: THe deck list HTML
    """
    card = Card.objects.get(pk=card_id)
    deck_cards = (
        DeckCard.objects.filter(deck__owner=request.user)
        .filter(card=card)
        .order_by("-deck__date_created")
    )
    card_count = deck_cards.aggregate(card_count=Sum("count"))["card_count"]
    deck_count = deck_cards.aggregate(deck_count=Count("deck_id"))["deck_count"]

    return render(
        request,
        "website/results/search_result_decks.html",
        {"deck_cards": deck_cards, "card_count": card_count, "deck_count": deck_count},
    )


def ajax_search_result_links(request: WSGIRequest, card_id: int) -> HttpResponse:
    """
    Gets the links HTML of a Card
    :param request: The user's request
    :param card_id: The ID of the Card
    :return: The link HTML
    """
    card: Card = Card.objects.get(pk=card_id)
    links = [
        {
            "name": "Search on Channel Fireball",
            "url": f"https://store.channelfireball.com/products/search?{urllib.parse.urlencode({'q': card.name})}",
        },
        {
            "name": "TCGPlayer Decks",
            "url": f"https://decks.tcgplayer.com/magic/deck/search?{urllib.parse.urlencode({'contains': card.name, 'page': 1})}",
        },
        {
            "name": "Card Analysis on EDHREC",
            "url": f"https://edhrec.com/route/?{urllib.parse.urlencode({'cc': card.faces.first().name})}",
        },
        {
            "name": "Search on DeckStats",
            "url": f"https://deckstats.net/decks/search/?{urllib.parse.urlencode({'search_cards[]': card.name})}",
        },
        {
            "name": "MTGTop8 decks",
            "url": "https://mtgtop8.com/search?{}".format(
                urllib.parse.urlencode(
                    {"MD_check": 1, "SB_check": 1, "cards": card.faces.first().name}
                )
            ),
        },
        {
            "name": "Search on Starcity Games",
            "url": f"https://starcitygames.com/search/?{urllib.parse.urlencode({'search_query': card.name})}",
        },
        {
            "name": "Search on Scryfall",
            "url": f"https://scryfall.com/search?q={urllib.parse.urlencode({'name': card.name})}",
        },
        {
            "name": "Card Kingdom",
            "url": "https://www.cardkingdom.com/catalog/search?{}".format(

sylvan_library/website/views/index.py
from django.core.handlers.wsgi import WSGIRequest
from django.http import HttpResponse
from django.shortcuts import render

from sylvan_library.cards.models.sets import Set


def index(request: WSGIRequest) -> HttpResponse:
    """
    The index page of this site
    :param request: The
    :return:
    """
    context = {"sets": Set.objects.all()}
    return render(request, "website/index.html", context)

sylvan_library/website/views/search.py
from django.http import HttpResponse, HttpRequest
from django.shortcuts import render

from website.forms import QuerySearchForm
from website.pagination import get_page_buttons


def card_search(request: HttpRequest) -> HttpResponse:
    """
    The view for when a user searches by card name
    :param request: The user's request
    :return: The HTTP Response
    """
    query_form = QuerySearchForm(request.GET)
    search, query_context = query_form.get_search(user=request.user)

    return render(
        request,
        "website/search.html",
        {
            "query_form": query_form,
            "results": search.results,
            "result_count": search.paginator.count,
            "page": search.page,
            "page_buttons": get_page_buttons(
                search.paginator, query_form.get_page_number(), 3
            ),
            "page_title": (
                f"{search.query_string} - Sylvan Library"
                if search.query_string
                else "Sylvan Library"
            ),
            "pretty_query_message": search.get_pretty_str(query_context),
            "error_message": search.error_message,
        },
    )

sylvan_library/website/views/sets.py
from typing import List

from django.core.handlers.wsgi import WSGIRequest
from django.shortcuts import render

from sylvan_library.cards.models.sets import Set


def set_list(request: WSGIRequest):
    """
    View for the list of all sets
    """
    all_sets = list(Set.objects.order_by("-release_date"))
    root_sets = [card_set for card_set in all_sets if not card_set.parent_set_id]

    serialised_sets = [
        serialise_set(card_set, all_sets, depth=1) for card_set in root_sets
    ]

    return render(request, "website/set_list.html", {"set_tree": serialised_sets})


def serialise_set(card_set: Set, all_sets: List[Set], depth: int):
    """
    Serialises the data for a single set
    :param card_set:
    :param all_sets:
    :param depth:
    :return:
    """
    return {
        "name": card_set.name,
        "code": card_set.code,
        "size": card_set.total_set_size,
        "release_date": card_set.release_date,
        "depth": depth,
        "child_sets": [
            serialise_set(child_set, all_sets, depth + 1)
            for child_set in all_sets
            if child_set.parent_set_id == card_set.id
        ],
    }

sylvan_library/website/templates/website/decks/deck_edit.html
{% extends 'website/base.html' %}
{% load widget_tweaks %}
{% load static %}

{% block head %}
    {{ deck_form.media.css }}
    {{ deck_form.media.js }}
    <script>
        let DECK_CARD_SEARCH_URL = '{% url 'website:deck_card_search' %}';
    </script>
    <script src="{% static "js/decks.js" %}" type="text/javascript"></script>
{% endblock %}

{% block content %}
    <div class="body-content">
        <div class="main-content">
            <form method="post"
                  action="{% spaceless %}
{% if deck_form.instance.id %}
    {% url 'website:deck_edit' deck_id=deck_form.instance.id %}
{% else %}
    {% url 'website:create_deck' %}
{% endif %}
{% endspaceless %}">
                {% csrf_token %}
                <div class="group-container">
                    <div class="row">
                        <div class="field-container">
                            {{ deck_form.name.label_tag }}
                            {{ deck_form.name }}
                        </div>
                        <div class="field-container">
                            {{ deck_form.subtitle.label_tag }}
                            {{ deck_form.subtitle }}
                        </div>
                        <div class="field-container">
                            {{ deck_form.format.label_tag }}
                            {{ deck_form.format }}
                        </div>
                        <div class="field-container">
                            {{ deck_form.date_created.label_tag }}
                            {% render_field deck_form.date_created type="date" %}
                            {{ deck_form.date_created.errors }}
                        </div>
                    </div>
                    <div class="row">
                        <div class="field-container">
                            {{ deck_form.description.label_tag }}
                            {{ deck_form.description }}
                        </div>
                    </div>
                </div>

                <div class="group-container">
                    <div class="row">
                        <div class="column">
                            <div class="row">
                                <div class="field-container">
                                    <label for="card-input">Card</label>
                                    <input id="card-input"/>
                                </div>
                            </div>
                            <div class="row">
                                <div class="field-container">
                                    {{ deck_form.quantity.label_tag }}
                                    {{ deck_form.quantity }}
                                </div>
                                <div class="field-container">
                                    {{ deck_form.card_board.label_tag }}
                                    {{ deck_form.card_board }}
                                </div>

                            </div>
                            <div class="row">
                                <button class="js-add-card-to-board-btn">Add card to board >></button>
                            </div>
                        </div>
                        <div class="column">
                            <div class="field-container">
                                <div class="search-result-tab-container">

                                    <div class="tab-container js-deck-board-tab-container" data-selected-tab="main">
                                        <ul class="tab-list">
                                            <li class="tab js-board-tab selected"
                                                data-tab-type="main">
                                                Main
                                            </li>
                                            <li class="tab js-board-tab"
                                                data-tab-type="side">
                                                Side
                                            </li>
                                            <li class="tab js-board-tab"
                                                data-tab-type="maybe">
                                                Maybe
                                            </li>
                                            <li class="tab js-board-tab"
                                                data-tab-type="acquire">
                                                Acquire
                                            </li>
                                        </ul>
                                        <div class="js-board-tab-content"
                                             data-tab-type="main">
                                            {% render_field deck_form.main_board rows="20" %}
                                        </div>
                                        <div class="js-board-tab-content"
                                             data-tab-type="side"
                                             style="display:none;">
                                            {% render_field deck_form.side_board rows="20" %}
                                        </div>
                                        <div class="js-board-tab-content"
                                             data-tab-type="maybe"
                                             style="display:none;">
                                            {% render_field deck_form.maybe_board rows="20" %}
                                        </div>
                                        <div class="js-board-tab-content"
                                             data-tab-type="acquire"
                                             style="display:none;">
                                            {% render_field deck_form.acquire_board rows="20" %}
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="group-container">
                    <div class="row">
                        <div class="field-container">
                            {{ deck_form.exclude_colours.label_tag }}
                            {{ deck_form.exclude_colours }}
                        </div>
                    </div>
                </div>

                <div class="group-container">
                    <div class="row">
                        <div class="field-container" style="flex-direction: row;">
                            {{ deck_form.is_prototype.label_tag }}
                            {{ deck_form.is_prototype }}
                        </div>
                        <div class="field-container" style="flex-direction: row;">
                            {{ deck_form.is_private.label_tag }}
                            {{ deck_form.is_private }}
                        </div>
                    </div>
                </div>

                {% if deck_form.errors %}
                    <div class="group-container">

                        {% for field, errors in deck_form.errors.items %}
                            {% for error in errors %}
                                <div>
                                    <strong>{{ error|escape }}</strong>
                                </div>
                            {% endfor %}
                        {% endfor %}
                        {{ deck_form.skip_validation.label_tag }}
                        {{ deck_form.skip_validation }}
                    </div>
                {% endif %}

                <div class="group-container">
                    <div class="row">
                        <input type="submit" name="save" value="Save"/>
                        <input type="submit" name="save_continue" value="Save &amp; Continue"/>
                        <a href="{% url 'website:decks' %}">Cancel</a>
                    </div>
                </div>
            </form>
        </div>
    </div>
{% endblock %}

sylvan_library/website/templates/website/decks/deck_stats.html
{% extends 'website/base.html' %}
{% load static %}
{% block content %}
    <div class="body-content">
        <div class="main-content" style="color:white;">
            <div class="group-container">
                <div class="field-container">
                    <h2>Some unused Cards</h2>
                    <ul>
                        {% for unused_card in unused_cards %}
                            <li>
                                {% include "website/card_link.html" with card=unused_card.card preferred_printing=unused_card.preferred_printing %}
                            </li>
                        {% endfor %}
                    </ul>
                    <h2>Some unused commanders</h2>
                    <ul>
                        {% for unused_card in unused_commanders %}
                            <li>
                                {% include "website/card_link.html" with card=unused_card.card preferred_printing=unused_card.preferred_printing %}
                            </li>
                        {% endfor %}
                    </ul>
                    <h2>Partner Pairings</h2>
                    <ul>
                        {% for partner_pair in partner_pairs %}
                            <li>
                                {% include "website/card_link.html" with card=partner_pair.partner_1.card preferred_printing=partner_pair.partner_1.preferred_printing %}
                                //
                                {% include "website/card_link.html" with card=partner_pair.partner_2.card preferred_printing=partner_pair.partner_2.preferred_printing %}
                            </li>
                        {% endfor %}
                    </ul>
                    <h2>Background Pairings</h2>
                    <ul>
                        {% for background_pair in background_pairs %}
                            <li>
                                {% include "website/card_link.html" with card=background_pair.choose_background.card preferred_printing=background_pair.choose_background.preferred_printing %}
                                //
                                {% include "website/card_link.html" with card=background_pair.background.card preferred_printing=background_pair.background.preferred_printing %}
                            </li>
                        {% endfor %}
                    </ul>
                    <a href="{% url "website:change_unused_decks" %}">See more unused cards</a>
                    <h2>Decks</h2> {{ deck_count }}
                    <h2>Warnings</h2>
                    {% for warning in deck_warnings %}
                        <div>
                            <a href="{% url "website:deck_view" deck_id=warning.deck.id %}">{{ warning.deck.name }}: </a>
                            {{ warning.msg }}
                        </div>
                    {% endfor %}
                </div>
            </div>
        </div>
    </div>
{% endblock %}

sylvan_library/website/templates/website/decks/deck_view.html
{% extends 'website/base.html' %}
{% load widget_tweaks %}
{% load static %}
{% load deck_templatetags %}
{% block head %}
    <script src="{% static "js/decks.js" %}" type="text/javascript"></script>
{% endblock %}
{% block content %}
    <div class="body-content">
        <div class="main-content" style="color:white;">
            <div class="group-container">
                <div class="field-container">
                    <h1>{{ deck.name }} {% if deck.is_prototype %}<em>[prototype]</em>{% endif %}</h1>
                    <h2>{{ deck.subtitle }}</h2>

                </div>
                <div class="field-container">
                    {{ deck.description|safe }}
                </div>
                <div class="field-container">
                    {{ deck.date_created }}
                </div>
                <div>
                    <canvas class="js-mini-deck-chart" height="75px" data-deck-id="{{ deck.id }}"></canvas>
                </div>
            </div>
            <div class="group-container">
                <div class="deck-card-list">
                    <div style="font-weight: bold;">Main {{ deck.get_mainboard_count }}</div>
                    {% for card_group in deck.get_card_groups %}
                        {% if card_group.cards %}
                            <div class="card-group">
                                <div class="group-title">{{ card_group.cards|deck_group_count }} {{ card_group.name }}
                                    {# Add land total if there are modal dfc cards #}
                                    {% if card_group.name == 'Lands' and card_group.cards|deck_group_count != deck.get_total_land_count %}
                                        ({{ deck.get_total_land_count }} <i class="ms ms-land"></i>)
                                    {% endif %}
                                </div>
                                {% for deck_card in card_group.cards %}
                                    {% include "website/decks/deck_card.html" with deck_card=deck_card %}
                                {% endfor %}
                            </div>
                        {% endif %}
                    {% endfor %}
                    {% if deck|board_cards:'side' %}
                        <div class="card-group">
                            <div class="group-title">Sideboard</div>
                            {% for deck_card in deck|board_cards:'side' %}
                                {% include "website/decks/deck_card.html" with deck_card=deck_card %}
                            {% endfor %}
                        </div>
                    {% endif %}
                </div>
            </div>
            <div class="group-container">
                <div class="deck-action-bar">
                    <a class="action-button" href="{% url 'website:decks' %}">Back</a>
                    <a class="action-button" href="{% url 'website:deck_edit' deck_id=deck.id %}">Edit</a>
                </div>
            </div>
        </div>
    </div>
{% endblock %}