sylvan_library/conf/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include, re_path
from sylvan_library.frontend import views as frontend_views

urlpatterns = [
    # Django and API routes should come first
    path("website/", include("sylvan_library.website.urls")),
    path("api/cards/", include("sylvan_library.cards.urls")),
    path("admin/", admin.site.urls),
    path("api-auth/", include("rest_framework.urls", namespace="rest_framework")),
    path("tinymce/", include("tinymce.urls")),
]

if settings.DEBUG_TOOLBAR:
    import debug_toolbar

    urlpatterns.append(path("__debug__/", include(debug_toolbar.urls)))

# A catch-all route to render the React application.
# This should be the last pattern in the list.
urlpatterns.append(re_path(r"^react/.*$", frontend_views.index, name="react-app"))

sylvan_library/website/urls.py
"""
Urls for the website app
"""

from django.urls import path

from sylvan_library.website import views

# pylint: disable=invalid-name
app_name = "website"
urlpatterns = [
    path("", views.index, name="index"),
    path("search/", views.card_search, name="card_search"),
    path("set_list/", views.set_list, name="set_list"),
    path(
        "ajax/search_result_details/<int:printing_id>/",
        views.ajax_search_result_details,
        name="ajax_search_result_details",
    ),
    path(
        "ajax/search_result_rulings/<int:card_id>/",
        views.ajax_search_result_rulings,
        name="ajax_search_result_rulings",
    ),
    path(
        "ajax/search_result_languages/<int:printing_id>/",
        views.ajax_search_result_languages,
        name="ajax_search_result_languages",
    ),
    path(
        "ajax/search_result_ownership/<int:card_id>/",
        views.ajax_search_result_ownership,
        name="ajax_search_result_ownership",
    ),
    path(
        "ajax/search_result_add/<int:printing_id>/",
        views.ajax_search_result_add,
        name="ajax_search_result_add",
    ),
    path(
        "ajax/card_printing_image/<int:printing_id>/",
        views.ajax_card_printing_image,
        name="ajax_card_printing_image",
    ),
    path(
        "ajax/change_card_ownership",
        views.ajax_change_card_ownership,
        name="ajax_change_card_ownership",
    ),
    path(
        "ajax/ownership_summary/<int:card_id>/",
        views.ajax_ownership_summary,
        name="ajax_ownership_summary",
    ),
    path(
        "ajax/search_result_set_summary/<int:printing_id>/",
        views.ajax_search_result_set_summary,
        name="ajax_search_result_set_summary",
    ),
    path(
        "ajax/search_result_decks/<int:card_id>/",
        views.ajax_search_result_decks,
        name="ajax_search_result_decks",
    ),
    path(
        "ajax/search_result_links/<int:card_id>/",
        views.ajax_search_result_links,
        name="ajax_search_result_links",
    ),
    path(
        "ajax/search_result_prices/<int:card_printing_id>/",
        views.ajax_search_result_prices,
        name="ajax_search_result_prices",
    ),
    path(
        "ajax/search_result_price_json/<int:card_printing_id>/",
        views.ajax_search_result_price_json,
        name="ajax_search_result_price_json",
    ),
    # Decks
    path("decks/card/", views.deck_card_search, name="deck_card_search"),
    path("decks/", views.deck_list, name="decks"),
    path("decks/create/", views.deck_create, name="create_deck"),
    path("decks/stats", views.deck_stats, name="deck_stats"),
    path("decks/<int:deck_id>/", views.deck_view, name="deck_view"),
    path("decks/<int:deck_id>/edit", views.deck_edit, name="deck_edit"),
    path(
        "decks/<int:deck_id>/colour_weights",
        views.deck_colour_weights,
        name="deck_colour_weights",
    ),
    path(
        "decks/change_unused_decks",
        views.change_unused_decks,
        name="change_unused_decks",
    ),
]

sylvan_library/cards/models/card.py
"""
Module for Card related models
"""

import datetime
import logging
import random
from typing import Optional

from django.contrib.auth import get_user_model
from django.db import models
from django.db.models import Sum, IntegerField, Case, When

from sylvan_library.bitfield import BitField
from sylvan_library.cards.models.colour import Colour
from sylvan_library.cards.models.language import Language
from sylvan_library.cards.models.rarity import Rarity
from sylvan_library.cards.models.sets import Set

CARD_LAYOUT_CHOICES = (
    ("normal", "Normal"),
    ("split", "Split"),
    ("flip", "Flip"),
    ("transform", "Transform"),
    ("token", "Token"),
    ("planar", "Planar"),
    ("scheme", "Scheme"),
    ("leveler", "Leveler"),
    ("vanguard", "Vanguard"),
    ("meld", "Meld"),
    ("host", "Host"),
    ("augment", "Augment"),
    ("saga", "Saga"),
    ("emblem", "Emblem"),
    ("double_faced_token", "Double-faced Token"),
    ("aftermath", "Aftermath"),
    ("adventure", "Adventure"),
    ("modal_dfc", "Modal DFC"),
)

FRAME_EFFECT_CHOICES = (
    ("colorshifted", "colorshifted"),
    ("companion", "Companion"),
    ("compasslanddfc", "compasslanddfc"),
    ("devoid", "devoid"),
    ("draft", "draft"),
    ("extendedart", "extendedart"),
    ("inverted", "inverted"),
    ("legendary", "legendary"),
    ("miracle", "miracle"),
    ("mooneldrazidfc", "mooneldrazidfc"),
    ("nyxborn", "nyxborn"),
    ("nyxtouched", "nyxtouched"),
    ("originpwdfc", "originpwdfc"),
    ("showcase", "showcase"),
    ("sunmoondfc", "sunmoondfc"),
    ("tombstone", "tombstone"),
    ("waxingandwaningmoondfc", "Waxing and Waning Moon DFC"),
    ("fullart", "Full Art"),
)


# pylint: disable=too-many-instance-attributes
class Card(models.Model):
    """
    Model for a unique card
    """

    scryfall_oracle_id = models.CharField(max_length=36, unique=True)
    name = models.CharField(max_length=200)
    mana_value = models.FloatField()
    layout = models.CharField(max_length=50)
    is_reserved = models.BooleanField(default=False)
    edh_rec_rank = models.IntegerField(blank=True, null=True)
    is_token = models.BooleanField(default=False)
    colour_identity = BitField(flags=Colour.FLAG_CHOICES)
    colour_identity_count = models.IntegerField()

    @staticmethod
    def get_random_card() -> "Card":
        """
        Gets a card chosen at random
        :return:
        """
        last = Card.objects.count() - 1
        index = random.randint(0, last)
        return Card.objects.all()[index]

    # pylint: disable=invalid-str-returned
    def __str__(self) -> str:
        return self.name

    def get_user_ownership_count(
        self, user: get_user_model(), prefetched: bool = False
    ) -> int:
        """
        Returns the total number of cards that given user owns of this card
        :param prefetched: Whether to use prefetched data, or to get it from the database again
        :param user: The user who should own the card
        :return: The ownership total
        """
        if prefetched:
            return sum(
                ownership.count
                for card_printing in self.printings.all()
                for localisation in card_printing.localisations.all()
                for ownership in localisation.ownerships.all()
                if ownership.owner_id == user.id
            )

        return self.printings.aggregate(
            card_count=Sum(
                Case(
                    When(
                        localisations__ownerships__owner=user,
                        then="localisations__ownerships__count",
                    ),
                    output_field=IntegerField(),
                    default=0,
                )
            )
        )["card_count"]

    @property
    def is_wide(self) -> bool:
        """
        Returns whether or not this is an oversized card
        :return: True if this is an oversized card, otherwise False
        """
        return self.layout == "planar"

    def is_double_faced(self) -> bool:
        """
        Gets whether this card has another card on the back
        :return: True if this card has is dual-faced or not
        """
        return self.layout in ("transform", "meld", "modal_dfc")

    def has_other_half(self) -> bool:
        """
        Gets whether this card has another half (flip, split, transform etc.)
        :return: True if this card has another half, otherwise False
        """
        return self.layout in (
            "flip",
            "split",
            "transform",
            "meld",
            "aftermath",
            "adventure",
            "modal_dfc",
        )

    def is_land(self, only_land: bool = False) -> bool:
        """
        Returns whether this is a land card
        :return: True if this is a land card, otherwise False
        """
        generator = (
            any(_type.name == "Land" for _type in face.types.all())
            for face in self.faces.all()
        )
        if only_land:
            return all(generator)
        return any(generator)


class CardType(models.Model):
    """
    The type of any number of cards (e.g. Creature, Artifact, etc.)
    """

    name = models.CharField(max_length=50, unique=True)
    # Types that aren't listed in the MTGJSON type files are "automatically created"
    automatically_created = models.BooleanField(default=False)

    def __str__(self) -> str:
        return self.name


class CardSupertype(models.Model):
    """
    The supertype of any number of cards (e.g. Legendary, Basic, etc.)
    """

    name = models.CharField(max_length=50, unique=True)
    # Types that aren't listed in the MTGJSON type files are "automatically created"
    automatically_created = models.BooleanField(default=False)

    def __str__(self) -> str:
        return self.name


class CardSubtype(models.Model):
    """
    The subtype of any number of cards (e.g. Beast, Equipment, Aura etc.)
    """

    name = models.CharField(max_length=50, unique=True)
    # Types that aren't listed in the MTGJSON type files are "automatically created"
    automatically_created = models.BooleanField(default=False)

    def __str__(self) -> str:
        return self.name


class CardFace(models.Model):
    """
    A face of a card. Most cards only have a single face, but any flip/split/transform or other
    cards will have 2 faces. Who//What//When//Where//Why will have 5.
    """

    card = models.ForeignKey(Card, related_name="faces", on_delete=models.CASCADE)
    side = models.CharField(max_length=1, blank=True, null=True)

    name = models.CharField(max_length=200)

    mana_cost = models.CharField(max_length=50, blank=True, null=True)
    mana_value = models.FloatField()
    colour = BitField(flags=Colour.FLAG_CHOICES)
    colour_indicator = BitField(flags=Colour.FLAG_CHOICES)
    colour_count = models.IntegerField()
    colour_weight = models.IntegerField()
    colour_sort_key = models.IntegerField()

    power = models.CharField(max_length=20, blank=True, null=True)
    num_power = models.FloatField(default=0)
    toughness = models.CharField(max_length=20, blank=True, null=True)
    num_toughness = models.FloatField(default=0)
    loyalty = models.CharField(max_length=20, blank=True, null=True)
    num_loyalty = models.FloatField(default=0)

    type_line = models.CharField(max_length=200, blank=True, null=True)
    rules_text = models.CharField(max_length=1500, blank=True, null=True)

    hand_modifier = models.CharField(max_length=10, blank=True, null=True)
    num_hand_modifier = models.IntegerField(default=0)
    life_modifier = models.CharField(max_length=10, blank=True, null=True)
    num_life_modifier = models.IntegerField(default=0)

    types = models.ManyToManyField(CardType, related_name="card_faces")

    subtypes = models.ManyToManyField(
        CardSubtype, related_name="card_faces", blank=True
    )
    supertypes = models.ManyToManyField(
        CardSupertype, related_name="card_faces", blank=True
    )

    class Meta:
        unique_together = ("card", "side")
        ordering = ("side",)

    def __str__(self) -> str:
        if self.side:
            return f"{self.name} ({self.side})"
        return self.name


class CardPrinting(models.Model):
    """
    Model for a certain card printed in a certain set
    """

    scryfall_id = models.CharField(max_length=36, unique=True)
    number = models.CharField(max_length=10, blank=True, null=True)
    numerical_number = models.IntegerField(blank=True, null=True)

    # The border colour of the card if it differs from the border colour of the rest of the set
    # (e.g. basic lands in Unglued)
    border_colour = models.CharField(max_length=10, blank=True, null=True)

    frame_version = models.CharField(max_length=50, blank=True, null=True)

    set = models.ForeignKey(
        Set, related_name="card_printings", on_delete=models.CASCADE
    )
    card = models.ForeignKey(Card, related_name="printings", on_delete=models.CASCADE)
    rarity = models.ForeignKey(
        Rarity, related_name="printings", on_delete=models.CASCADE
    )
    latest_price = models.ForeignKey(
        "CardPrice",
        related_name="latest_printing",
        on_delete=models.SET_NULL,
        blank=True,
        null=True,
    )

    # If the card is in a duel deck product, can be a (left) or b (right).
    duel_deck_side = models.CharField(max_length=1, blank=True, null=True)

    # Set to true if this card was only released as part of a core box set.
    # These are technically part of the core sets and are tournament
    # legal despite not being available in boosters.
    is_starter = models.BooleanField()

    is_timeshifted = models.BooleanField()

    # Can the card be found in foil?
    has_foil = models.BooleanField(default=True)
    # Can the card be found in non-foil?
    has_non_foil = models.BooleanField(default=True)

    # The card has some kind of alternative variation to its printed counterpart.

sylvan_library/website/views/index.py
from django.core.handlers.wsgi import WSGIRequest
from django.http import HttpResponse
from django.shortcuts import render

from sylvan_library.cards.models.sets import Set


def index(request: WSGIRequest) -> HttpResponse:
    """
    The index page of this site
    :param request: The
    :return:
    """
    context = {"sets": Set.objects.all()}
    return render(request, "website/index.html", context)

sylvan_library/website/views/search.py
from django.http import HttpResponse, HttpRequest
from django.shortcuts import render

from website.forms import QuerySearchForm
from website.pagination import get_page_buttons


def card_search(request: HttpRequest) -> HttpResponse:
    """
    The view for when a user searches by card name
    :param request: The user's request
    :return: The HTTP Response
    """
    query_form = QuerySearchForm(request.GET)
    search, query_context = query_form.get_search(user=request.user)

    return render(
        request,
        "website/search.html",
        {
            "query_form": query_form,
            "results": search.results,
            "result_count": search.paginator.count,
            "page": search.page,
            "page_buttons": get_page_buttons(
                search.paginator, query_form.get_page_number(), 3
            ),
            "page_title": (
                f"{search.query_string} - Sylvan Library"
                if search.query_string
                else "Sylvan Library"
            ),
            "pretty_query_message": search.get_pretty_str(query_context),
            "error_message": search.error_message,
        },
    )

sylvan_library/website/views/sets.py
from typing import List

from django.core.handlers.wsgi import WSGIRequest
from django.shortcuts import render

from sylvan_library.cards.models.sets import Set


def set_list(request: WSGIRequest):
    """
    View for the list of all sets
    """
    all_sets = list(Set.objects.order_by("-release_date"))
    root_sets = [card_set for card_set in all_sets if not card_set.parent_set_id]

    serialised_sets = [
        serialise_set(card_set, all_sets, depth=1) for card_set in root_sets
    ]

    return render(request, "website/set_list.html", {"set_tree": serialised_sets})


def serialise_set(card_set: Set, all_sets: List[Set], depth: int):
    """
    Serialises the data for a single set
    :param card_set:
    :param all_sets:
    :param depth:
    :return:
    """
    return {
        "name": card_set.name,
        "code": card_set.code,
        "size": card_set.total_set_size,
        "release_date": card_set.release_date,
        "depth": depth,
        "child_sets": [
            serialise_set(child_set, all_sets, depth + 1)
            for child_set in all_sets
            if child_set.parent_set_id == card_set.id
        ],
    }

sylvan_library/website/templates/website/card_image.html
{% load card_image %}
{% load static %}

{% block content %}
    {% for face_printing in printing.face_printings.all %}
        <img class="card-image
        js-card-result-image
        {% if forloop.first %}side-front{% else %}side-back{% endif %}
                layout-{{ printing.card.layout }}
                {% if printing.card.is_wide %}wide{% endif %}
                {% if printing.card.is_double_faced %}flipping{% endif %}"
             src="{% static face_printing|card_face_printing_image_url|safe %}" alt="{{ printing.card.display_name }}"
             width="100"/>
    {% endfor %}
{% endblock %}

sylvan_library/website/templates/website/card_link.html
{% load card_image %}
{% load static %}
{% block content %}
    <span class="card-link js-card-link"
            {% if preferred_printing %}
          data-image-path="{% static preferred_printing|card_printing_image_url|safe %}"
            {% else %}
          data-image-path="{% static card|card_image_url|safe %}"
            {% endif %}
          data-layout="{{ card.layout }}"
          data-side="{{ card.side }}"
            {% if card.layout == 'aftermath' and card.side == 'b' %}
          data-rotation="-90"
            {% elif card.layout == 'flip' and card.side == 'b' %}
          data-rotation="180"
            {% else %}
          data-rotation="0"
            {% endif %}
    >
    <a href="{% url 'website:card_search' %}?query_string={{ card.name }}" rel="noreferrer"
       {% if newtab %}target="_blank"{% endif %}
    >{% if card_name %}{{ card_name }}{% else %}
        {{ card.name }}{% endif %}
    </a>
    </span>
{% endblock %}

sylvan_library/website/templates/website/index.html
{% extends 'website/base.html' %}
{% load static %}
{% block content %}
{% endblock %}

sylvan_library/website/templates/website/pager.html
{% load param_replace %}
<div class="pagination-container">
    <div class="page-button-list">
        {% for page_button in page_buttons %}
            <div class="page-button
                {% if page_button.enabled %}js-page-button{% else %}disabled{% endif %}
                {% if page_button.is_active %}is-active{% endif %}"
                 data-page-url="{% spaceless %}
                    {% if page_name == "prototype_page" %}
                        {% param_replace prototype_page=page_button.number %}
                    {% else %}
                        {% param_replace page=page_button.number %}
                    {% endif %}
                    {% endspaceless %}">
                <div class="page-button-text">
                    {% if page_button.is_previous %}
                        Previous
                    {% elif page_button.is_next %}
                        Next
                    {% elif page_button.is_spacer %}
                        ...
                    {% else %}
                        {{ page_button.number }}
                    {% endif %}</div>
            </div>
        {% endfor %}
    </div>
</div>

sylvan_library/website/templates/website/results.html
{% load staticfiles %}
{% block head %}
    <script src="{% static "js/search_result.js" %}" type="text/javascript"></script>
{% endblock %}
{% block content %}
    <div class="results-page">
        <div class="action-bar">
            <div class="action-bar-row">
                <div class="result-count-container">
                    <div class="results-count">
                        {{ result_count }} results found
                    </div>
                </div>
                <div class="select-group">
                    <select>
                        <option value="name.raw_asc">Name
                            (ascending)
                        </option>
                        <option value="name.raw_desc">Name
                            (descending)
                        </option>
                        <option value="_score_asc">Relevance
                            (ascending)
                        </option>
                        <option value="_score_desc">Relevance
                            (descending)
                        </option>
                        <option value="colors_asc">Colour
                            (ascending)
                        </option>
                        <option value="colors_desc">Colour
                            (descending)
                        </option>
                        <option value="cmc_asc">CMC (ascending)
                        </option>
                        <option value="cmc_desc">CMC
                            (descending)
                        </option>
                        <option value="multiverseids.number_asc"
                        >Card number
                            (ascending)
                        </option>
                        <option value="multiverseids.number_desc"
                        >Card number
                            (descending)
                        </option>
                        <option value="multiverseids.medPrice_asc"
                        >Paper Price
                            (ascending)
                        </option>
                        <option value="multiverseids.medPrice_desc"
                        >Paper Price
                            (descending)
                        </option>
                        <option value="multiverseids.mtgoPrice_asc"
                        >MTGO Price
                            (ascending)
                        </option>
                        <option selected="" value="multiverseids.mtgoPrice_desc"
                        >MTGO Price
                            (descending)
                        </option>
                    </select>
                </div>
            </div>
        </div>

        {% if results %}
            {% if page_buttons|length > 3 %}
                {% include "website/pager.html" with page_buttons=page_buttons %}
            {% endif %}
            <div class="search-result-list">
                {% for result in results %}
                    {% include "website/search_result.html" with card=result %}
                {% endfor %}
            </div>
            {% if page_buttons|length > 3 %}
                {% include "website/pager.html" with page_buttons=page_buttons %}
            {% endif %}
        {% else %}
            <div class="no-search-results">
                <div class="no-search-results-content">
                    No results found
                </div>
                <br/>
            </div>
        {% endif %}
    </div>
{% endblock %}

sylvan_library/website/templates/website/resuts.html
{% block content %}
    <div class="sk-layout__result sk-results-list">
        <div class="sk-results-list__action-bar sk-action-bar">
            <div class="sk-action-bar-row">
                <div class="sk-hits-stats" data-qa="hits-stats">
                    <div class="sk-hits-stats__info" data-qa="info">7
                        results found in 19ms
                    </div>
                </div>
                <div data-qa="options" class="sk-toggle">
                    <div class="sk-toggle-option sk-toggle__item" data-qa="option" data-key="grid"
                    >
                        <div data-qa="label" class="sk-toggle-option__text"
                        >Grid
                        </div>
                    </div>
                    <div class="sk-toggle-option sk-toggle__item is-active" data-qa="option"
                         data-key="list">
                        <div data-qa="label" class="sk-toggle-option__text"
                        >List
                        </div>
                    </div>
                    <div class="sk-toggle-option sk-toggle__item" data-qa="option" data-key="table"
                    >
                        <div data-qa="label" class="sk-toggle-option__text"
                        >Table
                        </div>
                    </div>
                </div>
                <div class="sk-select"><select
                >
                    <option value="name.raw_asc">Name
                        (ascending)
                    </option>
                    <option value="name.raw_desc">Name
                        (descending)
                    </option>
                    <option value="_score_asc">Relevance
                        (ascending)
                    </option>
                    <option value="_score_desc">Relevance
                        (descending)
                    </option>
                    <option value="colors_asc">Colour
                        (ascending)
                    </option>
                    <option value="colors_desc">Colour
                        (descending)
                    </option>
                    <option value="cmc_asc">CMC (ascending)
                    </option>
                    <option value="cmc_desc">CMC
                        (descending)
                    </option>
                    <option value="multiverseids.number_asc"
                    >Card number
                        (ascending)
                    </option>
                    <option value="multiverseids.number_desc"
                    >Card number
                        (descending)
                    </option>
                    <option value="multiverseids.medPrice_asc"
                    >Paper Price
                        (ascending)
                    </option>
                    <option value="multiverseids.medPrice_desc"
                    >Paper Price
                        (descending)
                    </option>
                    <option value="multiverseids.mtgoPrice_asc"
                    >MTGO Price
                        (ascending)
                    </option>
                    <option selected="" value="multiverseids.mtgoPrice_desc"
                    >MTGO Price
                        (descending)
                    </option>
                </select></div>
                <div data-qa="options" class="sk-toggle">
                    <div class="sk-toggle-option sk-toggle__item is-active" data-qa="option"
                         data-key="12">
                        <div data-qa="label" class="sk-toggle-option__text"
                        >12
                        </div>
                    </div>
                    <div class="sk-toggle-option sk-toggle__item" data-qa="option" data-key="24"
                    >
                        <div data-qa="label" class="sk-toggle-option__text"
                        >24
                        </div>
                    </div>
                    <div class="sk-toggle-option sk-toggle__item" data-qa="option" data-key="48"
                    >
                        <div data-qa="label" class="sk-toggle-option__text"
                        >48
                        </div>
                    </div>
                    <div class="sk-toggle-option sk-toggle__item" data-qa="option" data-key="96"
                    >
                        <div data-qa="label" class="sk-toggle-option__text"
                        >96
                        </div>
                    </div>
                </div>
            </div>
            <div class="sk-action-bar__filters">
                <noscript></noscript>
                <div>
                    <div class="sk-reset-filters">
                        <div class="sk-reset-filters__reset">Clear
                            all filters
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div data-qa="hits" class="sk-hits-list">
            {% for result in results %}
                {% include "website/search_result.html" with card=result %}
            {% endfor %}
        </div>
        <div class="sk-pagination-navigation is-numbered">
            <div data-qa="options" class="sk-toggle is-disabled">
                <div class="sk-toggle-option sk-toggle__item is-disabled" data-qa="option"
                     data-key="previous">
                    <div data-qa="label" class="sk-toggle-option__text"
                    >Previous
                    </div>
                </div>
                <div class="sk-toggle-option sk-toggle__item is-active" data-qa="option" data-key="1"
                >
                    <div data-qa="label" class="sk-toggle-option__text"
                    >1
                    </div>
                </div>
                <div class="sk-toggle-option sk-toggle__item is-disabled" data-qa="option"
                     data-key="next">
                    <div data-qa="label" class="sk-toggle-option__text"
                    >Next
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

sylvan_library/website/templates/website/search.html
{% extends 'website/base.html' %}
{% load widget_tweaks %}
{% block content %}
    <div class="body-content">
        {% include "website/results/results.html" %}
    </div>
{% endblock %}

sylvan_library/website/templates/website/top_bar.html
{% block content %}
    <div class="top-bar">
        <div class="top-bar-content">
            <a href="/" class="action-button">Sylvan Library</a>
            <a class="action-button" href="#">About</a>
            <div class="header-search-container">
                <form action="{% url 'website:card_search' %}" method="get">
                    <div class="search-icon"></div>
                    <input type="text" class="search-input js-search-bar-input"
                           name="query_string"
                           placeholder="Type to search"
                           value="{% if query_form %}{{ query_form.query_string.value }}{% endif %}">
                    <input type="submit" style="display: none;">
                </form>
            </div>
                <a class="action-button" href="{% url 'website:set_list' %}">All Sets</a>
            {% if not request.user.is_authenticated %}
                <a class="action-button" href="{% url 'admin:login' %}">Login</a>
                <a class="action-button" href="{% url 'admin:login' %}">Sign Up</a>
            {% else %}
                <a class="action-button profile-button js-profile-button" href="#">
                    {{ request.user.username }}
                </a>
                <div class="profile-container js-profile-container" style="display: none;" data-expanded="0">
                    <p>{{ request.user.username }} {{ request.user.email }}</p>
                    <p>Date joined {{ request.user.date_joined }}</p>
                    <p><a href="{% url 'website:decks' %}">My Decks</a></p>
                    <p><a href="{% url 'admin:logout' %}">Log out</a></p>
                </div>
            {% endif %}
        </div>
    </div>
{% endblock %}