sylvan_library/conf/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include, re_path
from sylvan_library.frontend import views as frontend_views

urlpatterns = [
    # Django and API routes should come first
    path("website/", include("sylvan_library.website.urls")),
    path("api/cards/", include("sylvan_library.cards.urls")),
    path("admin/", admin.site.urls),
    path("api-auth/", include("rest_framework.urls", namespace="rest_framework")),
    path("tinymce/", include("tinymce.urls")),
]

if settings.DEBUG_TOOLBAR:
    import debug_toolbar

    urlpatterns.append(path("__debug__/", include(debug_toolbar.urls)))

# A catch-all route to render the React application.
# This should be the last pattern in the list.
urlpatterns.append(re_path(r"^react/.*$", frontend_views.index, name="react-app"))

sylvan_library/website/urls.py
"""
Urls for the website app
"""

from django.urls import path

from sylvan_library.website import views

# pylint: disable=invalid-name
app_name = "website"
urlpatterns = [
    path("", views.index, name="index"),
    path("search/", views.card_search, name="card_search"),
    path("set_list/", views.set_list, name="set_list"),
    path(
        "ajax/search_result_details/<int:printing_id>/",
        views.ajax_search_result_details,
        name="ajax_search_result_details",
    ),
    path(
        "ajax/search_result_rulings/<int:card_id>/",
        views.ajax_search_result_rulings,
        name="ajax_search_result_rulings",
    ),
    path(
        "ajax/search_result_languages/<int:printing_id>/",
        views.ajax_search_result_languages,
        name="ajax_search_result_languages",
    ),
    path(
        "ajax/search_result_ownership/<int:card_id>/",
        views.ajax_search_result_ownership,
        name="ajax_search_result_ownership",
    ),
    path(
        "ajax/search_result_add/<int:printing_id>/",
        views.ajax_search_result_add,
        name="ajax_search_result_add",
    ),
    path(
        "ajax/card_printing_image/<int:printing_id>/",
        views.ajax_card_printing_image,
        name="ajax_card_printing_image",
    ),
    path(
        "ajax/change_card_ownership",
        views.ajax_change_card_ownership,
        name="ajax_change_card_ownership",
    ),
    path(
        "ajax/ownership_summary/<int:card_id>/",
        views.ajax_ownership_summary,
        name="ajax_ownership_summary",
    ),
    path(
        "ajax/search_result_set_summary/<int:printing_id>/",
        views.ajax_search_result_set_summary,
        name="ajax_search_result_set_summary",
    ),
    path(
        "ajax/search_result_decks/<int:card_id>/",
        views.ajax_search_result_decks,
        name="ajax_search_result_decks",
    ),
    path(
        "ajax/search_result_links/<int:card_id>/",
        views.ajax_search_result_links,
        name="ajax_search_result_links",
    ),
    path(
        "ajax/search_result_prices/<int:card_printing_id>/",
        views.ajax_search_result_prices,
        name="ajax_search_result_prices",
    ),
    path(
        "ajax/search_result_price_json/<int:card_printing_id>/",
        views.ajax_search_result_price_json,
        name="ajax_search_result_price_json",
    ),
    # Decks
    path("decks/card/", views.deck_card_search, name="deck_card_search"),
    path("decks/", views.deck_list, name="decks"),
    path("decks/create/", views.deck_create, name="create_deck"),
    path("decks/stats", views.deck_stats, name="deck_stats"),
    path("decks/<int:deck_id>/", views.deck_view, name="deck_view"),
    path("decks/<int:deck_id>/edit", views.deck_edit, name="deck_edit"),
    path(
        "decks/<int:deck_id>/colour_weights",
        views.deck_colour_weights,
        name="deck_colour_weights",
    ),
    path(
        "decks/change_unused_decks",
        views.change_unused_decks,
        name="change_unused_decks",
    ),
]

sylvan_library/website/views.py
"""
Module for all website views
"""
import datetime
import logging
import random
import urllib.parse
import urllib.request
from typing import Dict, Any, List

from django.contrib.auth.models import User
from django.core.exceptions import ValidationError, PermissionDenied
from django.core.handlers.wsgi import WSGIRequest
from django.core.paginator import Paginator
from django.db import transaction
from django.db.models import Sum, Count, Q
from django.http import HttpResponse, JsonResponse
from django.shortcuts import render, redirect

from cards.models.card import (
    CardPrinting,
    Card,
    UserOwnedCard,
    CardLocalisation,
    CardFace,
    UserCardChange,
)
from cards.models.colour import Colour
from cards.models.decks import DeckCard, Deck
from cards.models.language import Language
from cards.models.sets import Set
from cards.models.user import UserProps
from website.forms import (
    QuerySearchForm,
    ChangeCardOwnershipForm,
    DeckForm,
)
from website.pagination import get_page_buttons

logger = logging.getLogger("django")


def index(request: WSGIRequest) -> HttpResponse:
    """
    The index page of this site
    :param request: The
    :return:
    """
    context = {"sets": Set.objects.all()}
    return render(request, "website/index.html", context)


def name_search(request: WSGIRequest) -> HttpResponse:
    """
    The view for when a user searches by card name
    :param request: The user's request
    :return: The HTTP Response
    """
    query_form = QuerySearchForm(request.GET)
    query_form.user = request.user
    search = query_form.get_search()
    return render(
        request,
        "website/simple_search.html",
        {
            "query_form": query_form,
            "results": search.results,
            "result_count": search.paginator.count,
            "page": search.page,
            "page_buttons": get_page_buttons(
                search.paginator, query_form.get_page_number(), 3
            ),
            "page_title": f"{search.query_string} - Sylvan Library"
            if search.query_string
            else "Sylvan Library",
            "pretty_query_message": search.get_pretty_str(),
            "error_message": search.error_message,
        },
    )


def ajax_search_result_details(request: WSGIRequest, printing_id: int) -> HttpResponse:
    """
    Gets the details of a card in the result page
    :param request: The user's request
    :param printing_id: The ID of the CardPrinting
    :return: The HTTP response
    """
    printing = CardPrinting.objects.get(id=printing_id)
    return render(
        request, "website/results/search_result_details.html", {"printing": printing}
    )


def ajax_search_result_rulings(request: WSGIRequest, card_id: int) -> HttpResponse:
    """
    Returns the rulings of a card
    :param request: The user's request
    :param card_id: The ID of the Card
    :return: The rulings HTML
    """
    card = Card.objects.get(id=card_id)
    return render(request, "website/results/search_result_rulings.html", {"card": card})


def ajax_search_result_languages(
    request: WSGIRequest, printing_id: int
) -> HttpResponse:
    """
    Gets the languages HTML of a printing
    :param request: The user's request
    :param printing_id: The CardPrinting ID
    :return: The languages HTML
    """
    printing = CardPrinting.objects.get(id=printing_id)
    return render(
        request, "website/results/search_result_languages.html", {"printing": printing}
    )


def ajax_card_printing_image(request: WSGIRequest, printing_id: int) -> HttpResponse:
    """
    Gets the image view of a printing
    :param request: The user's request
    :param printing_id: The CardPrinting ID
    :return: The image HTML
    """
    printing = CardPrinting.objects.get(id=printing_id)
    return render(request, "website/card_image.html", {"printing": printing})


def ajax_search_result_add(request: WSGIRequest, printing_id: int) -> HttpResponse:
    """
    Gets the "Add card" form for a card printing
    :param request: The user's request
    :param printing_id: The CardPrinting ID
    :return: The add form HTML
    """
    printing = CardPrinting.objects.get(id=printing_id)
    form = ChangeCardOwnershipForm(printing)
    return render(
        request,
        "website/results/search_result_add.html",
        {"form": form, "printing": printing},
    )


def ajax_search_result_ownership(request: WSGIRequest, card_id: int) -> HttpResponse:
    """
    Gets the ownership list for a Card
    :param request: The user's request
    :param card_id: The Card ID
    :return: The ownership HTML
    """
    card = Card.objects.get(id=card_id)
    ownerships = (
        UserOwnedCard.objects.filter(owner=request.user)
        .filter(card_localisation__card_printing__card__id=card_id)
        .order_by("card_localisation__card_printing__set__release_date")
    )
    changes = (
        UserCardChange.objects.filter(owner=request.user)
        .filter(card_localisation__card_printing__card__id=card_id)
        .order_by("date")
    )
    return render(
        request,
        "website/results/search_result_ownership.html",
        {"card": card, "ownerships": ownerships, "changes": changes},
    )


def ajax_change_card_ownership(request: WSGIRequest) -> HttpResponse:
    """
    Applies an ownership change (adding or removing the amount that a card owns)
    :param request: The user's request
    :return: JSON containing whether the change was successful or not
    """
    if not request.POST.get("count"):
        return JsonResponse({"result": False, "error": "Invalid count"})

    try:
        with transaction.atomic():
            change_count = int(request.POST["count"])
            localisation_id = int(request.POST["localisation"])
            localisation = CardLocalisation.objects.get(pk=localisation_id)
            localisation.apply_user_change(change_count, request.user)
            return JsonResponse({"result": True})
    except CardLocalisation.DoesNotExist as ex:
        return JsonResponse({"result": False, "error": str(ex)})


def ajax_ownership_summary(request: WSGIRequest, card_id: int) -> HttpResponse:
    """
    Gets the ownership HTML summary
    :param request: The user's request
    :param card_id: The Card ID
    :return: The ownership summary HTML
    """
    card = Card.objects.get(id=card_id)
    return render(request, "website/results/ownership_summary.html", {"card": card})


def ajax_search_result_set_summary(
    request: WSGIRequest, printing_id: int
) -> HttpResponse:
    """
    Gets the set summary for a given CardPrinting
    :param request: The user's request
    :param printing_id: The CardPrinting ID
    :return: The set summary HTML
    """
    printing = CardPrinting.objects.prefetch_related(
        "card__printings__rarity",
        "card__printings__localisations__ownerships",
        "card__printings__localisations__language",
        "card__printings__localisations__localised_faces__image",
        "card__printings__face_printings__localised_faces__image",
        "card__printings__face_printings__localised_faces__localisation",
        "card__printings__set",
        "card__printings__rarity",
    ).get(id=printing_id)

    return render(
        request,
        "website/results/search_result_sets.html",
        {"card": printing.card, "selected_printing": printing},
    )


def ajax_search_result_decks(request: WSGIRequest, card_id: int) -> HttpResponse:
    """
    Gets the deck list used by a given card
    :param request: The user's request
    :param card_id: The ID of the Card to get the HTML for
    :return: THe deck list HTML
    """
    card = Card.objects.get(pk=card_id)
    deck_cards = (
        DeckCard.objects.filter(deck__owner=request.user)
        .filter(card=card)
        .order_by("-deck__date_created")
    )
    card_count = deck_cards.aggregate(card_count=Sum("count"))["card_count"]
    deck_count = deck_cards.aggregate(deck_count=Count("deck_id"))["deck_count"]

    return render(
        request,
        "website/results/search_result_decks.html",
        {"deck_cards": deck_cards, "card_count": card_count, "deck_count": deck_count},
    )


def ajax_search_result_links(request: WSGIRequest, card_id: int) -> HttpResponse:
    """
    Gets the links HTML of a Card
    :param request: The user's request
    :param card_id: The ID of the Card
    :return: The link HTML
    """
    card: Card = Card.objects.get(pk=card_id)
    links = [
        {
            "name": "Search on Channel Fireball",
            "url": f"https://store.channelfireball.com/products/search?{urllib.parse.urlencode({'q': card.name})}",
        },
        {
            "name": "TCGPlayer Decks",
            "url": f"https://decks.tcgplayer.com/magic/deck/search?{urllib.parse.urlencode({'contains': card.name, 'page': 1})}",
        },
        {
            "name": "Card Analysis on EDHREC",
            "url": f"https://edhrec.com/route/?{urllib.parse.urlencode({'cc': card.faces.first().name})}",
        },
        {
            "name": "Search on DeckStats",
            "url": f"https://deckstats.net/decks/search/?{urllib.parse.urlencode({'search_cards[]': card.name})}",
        },
        {
            "name": "MTGTop8 decks",
            "url": "https://mtgtop8.com/search?{}".format(
                urllib.parse.urlencode(
                    {"MD_check": 1, "SB_check": 1, "cards": card.faces.first().name}
                )
            ),
        },
        {
            "name": "Search on Starcity Games",
            "url": f"https://starcitygames.com/search/?{urllib.parse.urlencode({'search_query': card.name})}",
        },
        {
            "name": "Search on Scryfall",
            "url": f"https://scryfall.com/search?q={urllib.parse.urlencode({'name': card.name})}",
        },
        {
            "name": "Card Kingdom",
            "url": "https://www.cardkingdom.com/catalog/search?{}".format(

sylvan_library/website/views/index.py
from django.core.handlers.wsgi import WSGIRequest
from django.http import HttpResponse
from django.shortcuts import render

from sylvan_library.cards.models.sets import Set


def index(request: WSGIRequest) -> HttpResponse:
    """
    The index page of this site
    :param request: The
    :return:
    """
    context = {"sets": Set.objects.all()}
    return render(request, "website/index.html", context)

sylvan_library/website/views/search.py
from django.http import HttpResponse, HttpRequest
from django.shortcuts import render

from website.forms import QuerySearchForm
from website.pagination import get_page_buttons


def card_search(request: HttpRequest) -> HttpResponse:
    """
    The view for when a user searches by card name
    :param request: The user's request
    :return: The HTTP Response
    """
    query_form = QuerySearchForm(request.GET)
    search, query_context = query_form.get_search(user=request.user)

    return render(
        request,
        "website/search.html",
        {
            "query_form": query_form,
            "results": search.results,
            "result_count": search.paginator.count,
            "page": search.page,
            "page_buttons": get_page_buttons(
                search.paginator, query_form.get_page_number(), 3
            ),
            "page_title": (
                f"{search.query_string} - Sylvan Library"
                if search.query_string
                else "Sylvan Library"
            ),
            "pretty_query_message": search.get_pretty_str(query_context),
            "error_message": search.error_message,
        },
    )

sylvan_library/website/views/sets.py
from typing import List

from django.core.handlers.wsgi import WSGIRequest
from django.shortcuts import render

from sylvan_library.cards.models.sets import Set


def set_list(request: WSGIRequest):
    """
    View for the list of all sets
    """
    all_sets = list(Set.objects.order_by("-release_date"))
    root_sets = [card_set for card_set in all_sets if not card_set.parent_set_id]

    serialised_sets = [
        serialise_set(card_set, all_sets, depth=1) for card_set in root_sets
    ]

    return render(request, "website/set_list.html", {"set_tree": serialised_sets})


def serialise_set(card_set: Set, all_sets: List[Set], depth: int):
    """
    Serialises the data for a single set
    :param card_set:
    :param all_sets:
    :param depth:
    :return:
    """
    return {
        "name": card_set.name,
        "code": card_set.code,
        "size": card_set.total_set_size,
        "release_date": card_set.release_date,
        "depth": depth,
        "child_sets": [
            serialise_set(child_set, all_sets, depth + 1)
            for child_set in all_sets
            if child_set.parent_set_id == card_set.id
        ],
    }

sylvan_library/website/templates/website/results/ownership_summary.html
{% load card_ownership %}
{% with count=card|user_card_ownership_count:request.user %}
    {% if count > 0 %}
        <span class="disqus-comment-count"
              style="font-variant:small-caps;float:right;cursor:pointer;padding-right:8px;font-size:smaller;">
            You own: {{ count }}
        </span>
    {% endif %}
{% endwith %}

sylvan_library/website/templates/website/results/results.html
{% load static %}
{% block head %}
    <script src="{% static "js/search_result.js" %}" type="text/javascript"></script>
{% endblock %}
{% block content %}
    <div class="results-page">
        <div class="action-bar">
            <div class="action-bar-row">
                {% if error_message %}
                    <div class="result-count-container">
                        {{ error_message }}
                    </div>
                {% endif %}
                <div class="result-count-container">
                    <div class="results-count">
                        {{ result_count }} result{% if result_count != 1 %}s{% endif %} found where {{ pretty_query_message }}
                    </div>
                </div>
                <div class="select-group">
                    <select>
                        <option value="name.raw_asc">Name
                            (ascending)
                        </option>
                        <option value="name.raw_desc">Name
                            (descending)
                        </option>
                        <option value="_score_asc">Relevance
                            (ascending)
                        </option>
                        <option value="_score_desc">Relevance
                            (descending)
                        </option>
                        <option value="colors_asc">Colour
                            (ascending)
                        </option>
                        <option value="colors_desc">Colour
                            (descending)
                        </option>
                        <option value="manavalue_asc">Mana value (ascending)
                        </option>
                        <option value="manavalue_desc">Mana value
                            (descending)
                        </option>
                        <option value="multiverseids.number_asc"
                        >Card number
                            (ascending)
                        </option>
                        <option value="multiverseids.number_desc"
                        >Card number
                            (descending)
                        </option>
                        <option value="multiverseids.medPrice_asc"
                        >Paper Price
                            (ascending)
                        </option>
                        <option value="multiverseids.medPrice_desc"
                        >Paper Price
                            (descending)
                        </option>
                        <option value="multiverseids.mtgoPrice_asc"
                        >MTGO Price
                            (ascending)
                        </option>
                        <option selected="" value="multiverseids.mtgoPrice_desc"
                        >MTGO Price
                            (descending)
                        </option>
                    </select>
                </div>
            </div>
        </div>

        {% if results %}
            {% if page_buttons|length > 3 %}
                {% include "website/pager.html" with page_buttons=page_buttons %}
            {% endif %}
            <div class="search-result-list">
                {% for result in results %}
                    {% include "website/results/search_result.html" with card=result %}
                {% endfor %}
            </div>
            {% if page_buttons|length > 3 %}
                {% include "website/pager.html" with page_buttons=page_buttons %}
            {% endif %}
        {% else %}
            <div class="no-search-results">
                <div class="no-search-results-content">
                    No results found
                </div>
                <br/>
            </div>
        {% endif %}
    </div>
{% endblock %}

sylvan_library/website/templates/website/results/search_result_add.html
{% load widget_tweaks %}
{% block content %}
    <div class="extraDetails">
        <form action="{% url 'website:ajax_change_card_ownership' %}" class="js-change-card-ownership-form">
            {% csrf_token %}
            <p>Add to {{ printing.set.name }} (#{{ printing.number }})</p>
            <span class="text-input add-card-count-input">
                {{ form.count }}
            </span>
            <span class="select-group">
                {% render_field form.localisation %}
            </span>
            <input type="submit" class="action-button" value="Submit"/>
        </form>
    </div>
{% endblock %}

sylvan_library/website/templates/website/results/search_result_decks.html
{% block content %}
    <div class="extraDetails">
        {% if deck_cards %}
            {{ card_count }} used in {{ deck_count }} decks
            {% for deck_card in deck_cards %}
                <div>
                    <span class="subtitle">
                        {{ deck_card.count }}x in
                        <a href="{% url "website:deck_view" deck_id=deck_card.deck.id %}" target="_blank" class="card-link">
                            {{ deck_card.deck.name }} {{ deck_card.deck.subtitle|default_if_none:''}} ({{ deck_card.deck.date_created }})
                            {% if deck_card.board != 'main' %}
                                <em>({{ deck_card.get_board_display }}board)</em>
                            {% endif %}
                        </a>
                    </span>
                    <br/>
                </div>
            {% endfor %}
            {% else %}
            <span class="subtitle">You have never used this card in a deck</span>
        {% endif %}
    </div>
{% endblock %}

sylvan_library/website/templates/website/results/search_result_details.html
{% block content %}
    <div class="extraDetails">
        {% if printing.flavour_text %}
            <div>
            <span class="subtitle">
                <b>Flavour: </b>
            </span>
                <span class="subtitle">
                <span><i>{{ printing.flavour_text }}</i></span>
            </span>
                <br/>
            </div>
        {% endif %}
        <div>
            <span class="subtitle">
                <b>Artist: </b>
            </span>
            <div class="subtitle" style="display:inline-flex;">
                <a href="{% url 'website:card_search' %}?query_string=artist:'{{ printing.face_printings.first.artist }}'">
                    {{ printing.face_printings.first.artist }}
                </a>
            </div>
            <br/>

            <span class="subtitle">
                <b>Set: </b>
            </span>
            <div class="subtitle" style="display:inline-flex;">
                <a href="{% url 'website:card_search' %}?query_string=set:{{ printing.set.code }}">
                    {{ printing.set.name }}
                </a>
            </div>
            <br/>
            <span class="subtitle">
                <b>Release date: </b>
            </span>
            <div class="subtitle" style="display:inline-flex;">
                {{ printing.set.release_date }}
            </div>
            <br/>
            <span class="subtitle">
                <b>Number </b>
            </span>
            <div class="subtitle" style="display:inline-flex;">
                {{ printing.number }}/{{ printing.set.total_set_size }}
            </div>
            <br/>
            {% if printing.artist %}
                <span class="subtitle">
                    <b>Artist: </b>
                </span>
                <div class="subtitle" style="display:inline-flex;">
                    {{ printing.artist }}
                </div>
                <br/>
            {% endif %}
        </div>
        {% if printing.card.legalities.count > 0 %}
            <div>
            <span class="subtitle">
                <b>Legalities: </b>
            </span>
                {% for legality in printing.card.legalities.all %}
                    <div>
                        <span class="subtitle">
                            {{ legality.format.name }}:
                        </span>
                        <span class="subtitle {{ legality.restriction|lower }}">{{ legality.restriction }}</span>
                        <br/>
                    </div>
                {% endfor %}
            </div>
        {% endif %}
    </div>

{% endblock %}

sylvan_library/website/templates/website/results/search_result_languages.html
<div class="extraDetails">
    {% if printing.localisations.exists %}
        <div>
            {% for localisation in printing.localisations.all %}
                <div>
                    <span class="subtitle">
                        <b>{{ localisation.language.name }}: </b>
                    </span>
                    <span class="subtitle">
                        {{ localisation.card_name }}
                    </span>
                </div>
            {% endfor %}
        </div>
    {% else %}
        <span class="subtitle">No other languages!</span>
    {% endif %}
</div>

sylvan_library/website/templates/website/results/search_result_links.html
{% block content %}
    <div class="extraDetails">
        {% for link in links %}
            <span class="subtitle">
                <a href="{{ link.url }}" target="_blank" class="card-link">
                    {{ link.name }}
                    <i class="fa fa-external-link" aria-hidden="true"></i>
                </a>
            </span>
            <br/>
        {% endfor %}
    </div>
{% endblock %}

sylvan_library/website/templates/website/results/search_result_ownership.html
{% block content %}
    <div class="extraDetails">
        {% if ownerships.exists %}
            <div>
            <span class="subtitle">
                <b>You own: </b>
            </span>
                {% for ownership in ownerships.all %}
                    <div>
                        <i class="setIcon ss ss-2x ss-{{ ownership.card_localisation.card_printing.get_set_keyrune_code }}
                            {% if printing.set.code == 'TSB' %}
                                ss-timeshifted
                            {% else %}
                                ss-{{ ownership.card_localisation.card_printing.rarity.name | lower }}
                            {% endif %}"
                        ></i>
                        <span class="subtitle">
                            {{ ownership.count }} {{ ownership.card_localisation }}
                        </span>
                        <br/>
                    </div>
                {% endfor %}
            </div>
        {% else %}
            <span class="subtitle">You don't own {{ card.name }}
        {% endif %}
        {% if changes %}
            <span class="subtitle">
                <b>Changes: </b>
            </span>
            {% for change in changes %}
                <div>
                    <span class="subtitle">
                        {% if change.difference > 0 %}+{% endif %}{{ change.difference }}
                        {{ change.date }} {{ change.card_localisation }}
                    </span>
                    <br/>
                </div>
            {% endfor %}
        {% endif %}
    </div>

{% endblock %}

sylvan_library/website/templates/website/results/search_result_rulings.html
<div class="extraDetails">
    {% if card.rulings.exists %}
        <div>
            {% for ruling in card.rulings.all %}
                <div>
                    <span class="subtitle">
                        <b>{{ ruling.date }}: </b>
                    </span>
                    <span class="subtitle">
                        <div>{{ ruling.text }}</div>
                    </span>
                </div>
            {% endfor %}
        </div>
    {% else %}
        <span class="subtitle">No rulings!</span>
    {% endif %}
</div>

sylvan_library/website/templates/website/results/search_result_sets.html
{% load card_ownership %}
{% load card_image %}
{% load static %}
<p style="text-align:center;max-height:200px;overflow-y:auto;">
    {% for printing in card.printings.all %}
        {% with ownership_count=printing|user_cardprinting_ownership_count:request.user %}
            <i class="js-card-result-set-symbol
                    setIcon ss ss-2x
                    ss-{{ printing.get_set_keyrune_code }}
                    {% if ownership_count > 0 %}
                      owned
                    {% endif %}
                    {% if printing.set.code == 'TSB' %}
                        ss-timeshifted
                    {% else %}
                        ss-{{ printing.rarity.name | lower }}
                    {% endif %}
                    {% if printing.rarity.symbol != 'C' %}
                        ss-grad
                    {% endif %}
                    {% if printing == selected_printing %}
                        clicked
                    {% endif %}
                        {{ printing.rarity.symbol }}"
               data-card-printing-id="{{ printing.id }}"
               data-index="{{ forloop.counter }}"
               data-image-url="{% static printing|card_printing_image_url|safe %}"
                    {% if request.user.is_authenticated %}
                        {% if ownership_count > 0 %}
               title="{{ printing.set.name }}&#013;x {{ ownership_count }}"
                        {% else %}
               title="{{ printing.set.name }}"
                        {% endif %}
                    {% else %}
               title="{{ printing.set.name }}"
                    {% endif %}
            ></i>
        {% endwith %}
    {% endfor %}
</p>